### ISSUE TITLE
Pointer to current TaDiRAH outdated

### ISSUE THREAD

**Issue by vronk** [dhtaxonomy/TaDiRAH#35]
There is an [outdated link in the readme to the current version of TaDiRAH](https://github.com/dhtaxonomy/TaDiRAH/blob/master/readme.md?plain=1#L41).
Current right pointer is:
https://vocabs.dariah.eu/tadirah/

Also it would be probably good to formulate more clearly and prominently at the beginning of the readme that the version in the repo is outdated and that the current version is on DARIAH Vocabs

**Comment by christofs** [comment]
Thanks for pointing this out, I've updated the readme accordingly.
